### ISSUE TITLE
网页设计、APP设计、Banner、插画、图标设计、动画、3D页面

### ISSUE THREAD

**Issue by bojueLi** [2mui/ui-market-web#2]
以上页面有行业、格式、排序等搜索字段是哪个接口如何传参

**Comment by df1228** [comment]
网页设计、APP设计、Banner、插画、图标设计、动画、3D页面
query Items {
  items(where: {category_id: {_eq: 1}}) {
    category_id
    id
    title
  }
}

category_id   <------> 1.....7 分别对应网页设计、APP设计、Banner、插画、图标设计、动画、3D页面

**Comment by df1228** [comment]
推荐 where    featured: {_eq: true}
最新就按上传时间排序 order_by: {created_at: desc}
最热就按收藏数倒排 order_by: {likes_count: desc}
下载量就按下载次数倒排 order_by: {likes_count: desc}

eg: 

query Items {
  items(where: {category_id: {_eq: 1}, featured: {_eq: true}}, order_by: {downloads_count: desc}) {
    category_id
    id
    title
  }
}

**Comment by df1228** [comment]
格式这个先不管

**Comment by df1228** [comment]
行业 industry_id  where: {category_id: {_eq: 1}

后台管理数据的要更新一下
