### ISSUE TITLE
我的收藏、浏览记录、下载记录

### ISSUE THREAD

**Issue by bojueLi** [2mui/ui-market-web#3]
以上三个页面如何和用户关联，分别是哪个接口？我的收藏是文件夹有编辑删除功能对应的接口又是哪个？收藏还有二级列表页面也应该有对应的接口

**Comment by df1228** [comment]
{
  browse_histories(where: {user_id: {_eq: 1}}) {
    item_id
  }
}

{
  download_histories(where: {user_id: {_eq: 1}}) {
    item_id
  }
}


收藏表和收藏文件夹接口待发布 。。。。

**Comment by df1228** [comment]
收藏文件夹 folders 表
收藏 likes表

example:

```
{
  folders {
    id
    name
    user_id
    user {
      name
    }
  }
  likes {
    id
    item_id
    item {
      title
      detail
    }
    user_id
    user {
      id
    }
  }
}
```

xxx_id 是外键,  xxx 是关系
